s= set()
a1=input("Enter 8 no.: ")
s.add(int(a1))
a2=input("Enter 8 no.: ")
s.add(int(a2))
a3=input("Enter 8 no.: ")
s.add(int(a3))
a4=input("Enter 8 no.: ")
s.add(int(a4))
a5=input("Enter 8 no.: ")
s.add(int(a5))
a6=input("Enter 8 no.: ")
s.add(int(a6))
a7=input("Enter 8 no.: ")
s.add(int(a7))
a8=input("Enter 8 no.: ")
s.add(int(a8))
print(s)